// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWTNIyHqjTQB2qbYfsMU1o8sMapurhMWs',
    appId: '1:316270152747:web:924d99325c03cb151f2e6e',
    messagingSenderId: '316270152747',
    projectId: 'redtilt-ecom-app',
    authDomain: 'redtilt-ecom-app.firebaseapp.com',
    storageBucket: 'redtilt-ecom-app.appspot.com',
    measurementId: 'G-0CZK8W56WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDonbuoqfqJab46rM3NtU6ZczFDkZkUbAw',
    appId: '1:316270152747:android:586dcff61da4d7491f2e6e',
    messagingSenderId: '316270152747',
    projectId: 'redtilt-ecom-app',
    storageBucket: 'redtilt-ecom-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRJLHLr4CHvTJYWlMVUJFSEaG9SILpHo',
    appId: '1:316270152747:ios:0148c2ef8fe9892b1f2e6e',
    messagingSenderId: '316270152747',
    projectId: 'redtilt-ecom-app',
    storageBucket: 'redtilt-ecom-app.appspot.com',
    iosBundleId: 'redtilt.ecom.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRJLHLr4CHvTJYWlMVUJFSEaG9SILpHo',
    appId: '1:316270152747:ios:ebf0d93778e1b1a31f2e6e',
    messagingSenderId: '316270152747',
    projectId: 'redtilt-ecom-app',
    storageBucket: 'redtilt-ecom-app.appspot.com',
    iosBundleId: 'com.example.redtiltEcomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWTNIyHqjTQB2qbYfsMU1o8sMapurhMWs',
    appId: '1:316270152747:web:95aa0aa1aead6b6e1f2e6e',
    messagingSenderId: '316270152747',
    projectId: 'redtilt-ecom-app',
    authDomain: 'redtilt-ecom-app.firebaseapp.com',
    storageBucket: 'redtilt-ecom-app.appspot.com',
    measurementId: 'G-BYCWQZX960',
  );
}
